# -*- coding: utf-8 -*-
"""UrbanPulse2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ggKiO_zt5N3HApyMm6OKxNO_fIttr5y
"""

import pandas as pd

file_path = '/content/D47-Crimes (1)_1_0.csv'

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

display(df)

# Check the complete dataset
print("Dataset shape:", df.shape)

print("\nData types:")
print(df.dtypes)

print("\nDuplicate rows:", df.duplicated().sum())

print("\nUnique years:")
print(df['Year'].unique())

print("\nLast rows:")
display(df.tail())

# Remove the Total row
df_clean = df[df['Year'].astype(str).str.lower() != 'total'].copy()

# Make sure crime columns are numeric
df_clean['Fatal'] = pd.to_numeric(df_clean['Fatal'], errors='coerce')
df_clean['Non fatal'] = pd.to_numeric(df_clean['Non fatal'], errors='coerce')

# Calculate total crimes
df_clean['Total Crimes'] = df_clean['Fatal'] + df_clean['Non fatal']

print("Cleaned dataset:")
display(df_clean)

print("\nSummary:")
print(df_clean[['Fatal', 'Non fatal', 'Total Crimes']].describe())

import os

print("Files in Colab:\n")

for root, dirs, files in os.walk('/content'):
    for file in files:
        print(os.path.join(root, file))

import pandas as pd

crime_path = "/content/D47-Crimes (1)_1_0.csv"

crime_df = pd.read_csv(crime_path)

print("Shape:", crime_df.shape)
print("\nColumns:")
print(crime_df.columns.tolist())

print("\nFirst 5 rows:")
display(crime_df.head())

print("\nData types:")
print(crime_df.dtypes)

import pandas as pd
import matplotlib.pyplot as plt

# Clean Year safely
crime_df["Year_clean"] = pd.to_numeric(
    crime_df["Year"].astype(str).str.extract(r"(\d{4})")[0],
    errors="coerce"
)

# Remove rows where year could not be extracted
plot_df = crime_df.dropna(subset=["Year_clean"]).copy()

# Make sure crime counts are numeric
plot_df["Fatal"] = pd.to_numeric(plot_df["Fatal"], errors="coerce")
plot_df["Non fatal"] = pd.to_numeric(plot_df["Non fatal"], errors="coerce")

# Sort by year
plot_df = plot_df.sort_values("Year_clean")

# Plot
plt.figure(figsize=(10, 5))

plt.plot(
    plot_df["Year_clean"],
    plot_df["Fatal"],
    marker="o",
    label="Fatal"
)

plt.plot(
    plot_df["Year_clean"],
    plot_df["Non fatal"],
    marker="o",
    label="Non-Fatal"
)

plt.title("Bangalore Crime Trend by Year")
plt.xlabel("Year")
plt.ylabel("Number of Cases")
plt.legend()
plt.grid(True)

plt.show()

# Clean the Year column

crime_df["Year_clean"] = pd.to_numeric(
    crime_df["Year"].astype(str).str.extract(r"(\d{4})")[0],
    errors="coerce"
)

print(crime_df[["Year", "Year_clean"]])

import pandas as pd
import matplotlib.pyplot as plt

# Clean Year safely
crime_df["Year_clean"] = pd.to_numeric(
    crime_df["Year"].astype(str).str.extract(r"(\d{4})")[0],
    errors="coerce"
)

# Remove rows where year could not be extracted
plot_df = crime_df.dropna(subset=["Year_clean"]).copy()

# Make sure crime counts are numeric
plot_df["Fatal"] = pd.to_numeric(plot_df["Fatal"], errors="coerce")
plot_df["Non fatal"] = pd.to_numeric(plot_df["Non fatal"], errors="coerce")

# Sort by year
plot_df = plot_df.sort_values("Year_clean")

# Plot
plt.figure(figsize=(10, 5))

plt.plot(
    plot_df["Year_clean"],
    plot_df["Fatal"],
    marker="o",
    label="Fatal"
)

plt.plot(
    plot_df["Year_clean"],
    plot_df["Non fatal"],
    marker="o",
    label="Non-Fatal"
)

plt.title("Bangalore Crime Trend by Year")
plt.xlabel("Year")
plt.ylabel("Number of Cases")
plt.legend()
plt.grid(True)

plt.show()

# Year-over-Year Crime Analysis

analysis_df = plot_df.copy()

# Calculate total crimes
analysis_df["Total Crimes"] = (
    analysis_df["Fatal"] + analysis_df["Non fatal"]
)

# Calculate year-over-year percentage change
analysis_df["YoY Change %"] = (
    analysis_df["Total Crimes"]
    .pct_change() * 100
)

# Display results
print("===== YEAR-OVER-YEAR CRIME ANALYSIS =====")

display(
    analysis_df[
        ["Year_clean", "Fatal", "Non fatal",
         "Total Crimes", "YoY Change %"]
    ].round(2)
)

# Highest increase
increase = analysis_df.loc[
    analysis_df["YoY Change %"].idxmax()
]

# Highest decrease
decrease = analysis_df.loc[
    analysis_df["YoY Change %"].idxmin()
]

print("\n===== KEY INSIGHTS =====")

print(
    f"Highest increase: "
    f"{int(increase['Year_clean'])} "
    f"({increase['YoY Change %']:.2f}%)"
)

print(
    f"Highest decrease: "
    f"{int(decrease['Year_clean'])} "
    f"({decrease['YoY Change %']:.2f}%)"
)

# Crime Severity Analysis

severity_df = analysis_df.copy()

# Fatal percentage
severity_df["Fatal %"] = (
    severity_df["Fatal"] /
    severity_df["Total Crimes"]
) * 100

# Non-fatal percentage
severity_df["Non-Fatal %"] = (
    severity_df["Non fatal"] /
    severity_df["Total Crimes"]
) * 100

print("===== CRIME SEVERITY ANALYSIS =====")

display(
    severity_df[
        [
            "Year_clean",
            "Fatal",
            "Non fatal",
            "Total Crimes",
            "Fatal %",
            "Non-Fatal %"
        ]
    ].round(2)
)

# Overall statistics
total_fatal = severity_df["Fatal"].sum()
total_nonfatal = severity_df["Non fatal"].sum()
total_crimes = severity_df["Total Crimes"].sum()

overall_fatal_percentage = (
    total_fatal / total_crimes
) * 100

print("\n===== OVERALL =====")
print("Total Crimes:", int(total_crimes))
print("Total Fatal Cases:", int(total_fatal))
print("Total Non-Fatal Cases:", int(total_nonfatal))
print("Overall Fatal Percentage:", round(overall_fatal_percentage, 2), "%")

# Year with highest fatal percentage
highest_severity = severity_df.loc[
    severity_df["Fatal %"].idxmax()
]

print("\nHighest Fatal Percentage:")
print(
    int(highest_severity["Year_clean"]),
    "->",
    round(highest_severity["Fatal %"], 2),
    "%"
)

# ==========================================
# URBANPULSE - CITY CRIME RISK SCORE
# ==========================================

risk_df = severity_df.copy()

# Normalize Total Crimes (0-100)
total_min = risk_df["Total Crimes"].min()
total_max = risk_df["Total Crimes"].max()

risk_df["Crime Volume Score"] = (
    (risk_df["Total Crimes"] - total_min) /
    (total_max - total_min)
) * 100

# Normalize Fatal Percentage (0-100)
fatal_min = risk_df["Fatal %"].min()
fatal_max = risk_df["Fatal %"].max()

risk_df["Severity Score"] = (
    (risk_df["Fatal %"] - fatal_min) /
    (fatal_max - fatal_min)
) * 100

# Final UrbanPulse Risk Score
# 60% crime volume + 40% severity
risk_df["Risk Score"] = (
    0.60 * risk_df["Crime Volume Score"] +
    0.40 * risk_df["Severity Score"]
)

# Risk category
def risk_category(score):
    if score >= 70:
        return "High Risk"
    elif score >= 40:
        return "Medium Risk"
    else:
        return "Low Risk"

risk_df["Risk Level"] = risk_df["Risk Score"].apply(risk_category)

# Display result
display(
    risk_df[
        [
            "Year_clean",
            "Total Crimes",
            "Fatal %",
            "Crime Volume Score",
            "Severity Score",
            "Risk Score",
            "Risk Level"
        ]
    ].round(2)
)

# Highest-risk year
highest_risk = risk_df.loc[risk_df["Risk Score"].idxmax()]

print("\n===== URBANPULSE KEY RISK INSIGHT =====")
print(
    f"Highest Risk Year: {int(highest_risk['Year_clean'])}"
)
print(
    f"Risk Score: {highest_risk['Risk Score']:.2f}/100"
)
print(
    f"Risk Level: {highest_risk['Risk Level']}"
)

import glob
import xml.etree.ElementTree as ET
import pandas as pd

# Automatically find all KML files
kml_files = glob.glob("/content/*.kml")

print("KML files found:")
for i, f in enumerate(kml_files):
    print(i, f)

# Use the first KML file
kml_path = kml_files[0]

print("\nUsing:", kml_path)

tree = ET.parse(kml_path)
root = tree.getroot()

rows = []

for placemark in root.iter():
    name = None
    coordinates = None

    for child in placemark.iter():
        tag = child.tag.split("}")[-1]

        if tag == "name" and child.text:
            name = child.text.strip()

        elif tag == "coordinates" and child.text:
            coordinates = child.text.strip()

    if name and coordinates:
        coord = coordinates.split(",")

        if len(coord) >= 2:
            try:
                longitude = float(coord[0])
                latitude = float(coord[1])

                rows.append({
                    "Police Station": name,
                    "Latitude": latitude,
                    "Longitude": longitude
                })

            except ValueError:
                pass

police_df = pd.DataFrame(rows)

print("\nNumber of police stations:", len(police_df))

display(police_df.head(10))

import os

print("KML files in Colab:\n")

for file in os.listdir("/content"):
    if file.lower().endswith(".kml"):
        print(file)

import glob
import xml.etree.ElementTree as ET

print("===== KML STRUCTURE CHECK =====")

kml_files = glob.glob("/content/*.kml")

for kml_path in kml_files:
    print("\nFILE:", kml_path)

    try:
        tree = ET.parse(kml_path)
        root = tree.getroot()

        print("Root:", root.tag)

        # Find all elements containing useful location information
        for elem in root.iter():
            tag = elem.tag.split("}")[-1]

            if tag in ["Placemark", "name", "coordinates"]:
                text = (elem.text or "").strip()

                if text:
                    print(f"{tag}: {text[:200]}")

    except Exception as e:
        print("ERROR:", e)

import glob
import xml.etree.ElementTree as ET
import pandas as pd

rows = []

for kml_path in glob.glob("/content/*.kml"):

    tree = ET.parse(kml_path)
    root = tree.getroot()

    # Get the layer/station name
    names = []
    for elem in root.iter():
        if elem.tag.split("}")[-1] == "name" and elem.text:
            names.append(elem.text.strip())

    layer_name = names[0] if names else "Police Station"

    # Extract EVERY coordinate
    for elem in root.iter():

        if elem.tag.split("}")[-1] == "coordinates":

            text = (elem.text or "").strip()

            # KML can contain multiple coordinates in one element
            for item in text.replace("\n", " ").split():

                parts = item.split(",")

                if len(parts) >= 2:

                    try:
                        longitude = float(parts[0])
                        latitude = float(parts[1])

                        rows.append({
                            "Police Station": layer_name,
                            "Latitude": latitude,
                            "Longitude": longitude
                        })

                    except ValueError:
                        pass


# Create dataframe
police_df = pd.DataFrame(rows)

# Remove exact duplicate coordinates
police_df = police_df.drop_duplicates(
    subset=["Latitude", "Longitude"]
).reset_index(drop=True)

print("Total unique location points:", len(police_df))

display(police_df.head(20))

import folium

# Create Bengaluru map
m = folium.Map(
    location=[12.9716, 77.5946],
    zoom_start=11
)

# Add police/location markers from extracted KML data
for _, row in police_df.iterrows():
    folium.Marker(
        location=[row["Latitude"], row["Longitude"]],
        popup=row["Police Station"],
        tooltip=row["Police Station"],
        icon=folium.Icon(icon="info-sign")
    ).add_to(m)

# Display map
m

# ============================================
# URBANPULSE - INTERACTIVE POLICE STATION MAP
# With Crime & Risk Information
# ============================================

import folium

# Create Bengaluru map
m = folium.Map(
    location=[12.9716, 77.5946],
    zoom_start=11
)

# --------------------------------------------
# City-level crime information from analysis
# --------------------------------------------

total_crimes = 35971
total_fatal = 5437
total_non_fatal = 30534

overall_fatal_percentage = 15.11

highest_risk_year = 2016
highest_risk_score = 71.70
highest_risk_level = "High Risk"

# --------------------------------------------
# Add police station markers
# --------------------------------------------

for _, row in police_df.iterrows():

    # Popup information
    popup_html = f"""
    <div style="width:280px">

        <h4 style="margin-bottom:8px;">
            🚓 {row['Police Station']}
        </h4>

        <b>Location</b><br>
        Latitude: {row['Latitude']:.6f}<br>
        Longitude: {row['Longitude']:.6f}

        <hr>

        <h4>🏙️ UrbanPulse Crime Information</h4>

        <b>Total Crimes:</b> {total_crimes:,}<br>
        <b>Fatal Crimes:</b> {total_fatal:,}<br>
        <b>Non-Fatal Crimes:</b> {total_non_fatal:,}<br>
        <b>Fatal Percentage:</b> {overall_fatal_percentage:.2f}%

        <hr>

        <h4>⚠️ Risk Analysis</h4>

        <b>Highest Risk Year:</b> {highest_risk_year}<br>
        <b>Risk Score:</b> {highest_risk_score:.2f}/100<br>
        <b>Risk Level:</b> {highest_risk_level}

        <hr>

        <small>
        Note: Crime statistics shown here are
        city-level statistics because the current
        crime dataset does not contain
        police-station-level crime counts.
        </small>

    </div>
    """

    folium.Marker(
        location=[
            row["Latitude"],
            row["Longitude"]
        ],

        popup=folium.Popup(
            popup_html,
            max_width=350
        ),

        tooltip=row["Police Station"],

        icon=folium.Icon(
            icon="info-sign",
            prefix="glyphicon"
        )

    ).add_to(m)


# --------------------------------------------
# Add city-level crime summary box
# --------------------------------------------

summary_html = f"""
<div style="
    position: fixed;
    top: 20px;
    right: 20px;
    width: 260px;
    background-color: white;
    border: 2px solid #333;
    border-radius: 8px;
    padding: 15px;
    z-index: 9999;
    font-size: 14px;
">

<h3 style="margin-top:0;">
🏙️ UrbanPulse
</h3>

<b>Crime Overview</b>

<hr>

Total Crimes:
<b>{total_crimes:,}</b><br>

Fatal Crimes:
<b>{total_fatal:,}</b><br>

Non-Fatal Crimes:
<b>{total_non_fatal:,}</b><br>

Fatal Percentage:
<b>{overall_fatal_percentage:.2f}%</b>

<hr>

<b>⚠️ Highest Risk</b><br>

Year:
<b>{highest_risk_year}</b><br>

Risk Score:
<b>{highest_risk_score:.2f}/100</b><br>

Risk Level:
<b>{highest_risk_level}</b>

</div>
"""

m.get_root().html.add_child(
    folium.Element(summary_html)
)

# --------------------------------------------
# Display map
# --------------------------------------------

m

import pandas as pd
import glob
import os
import re
from IPython.display import display
import ipywidgets as widgets

# ============================================================
# 1. FIND THE UPLOADED CSV FILES AUTOMATICALLY
# ============================================================

csv_files = glob.glob("/content/*.csv")

print("CSV files found:")
for f in csv_files:
    print(" -", os.path.basename(f))


# ============================================================
# 2. IDENTIFY THE MAIN D47 CRIME DATASET
# ============================================================

d47_file = None

for f in csv_files:
    try:
        df_test = pd.read_csv(f)
        cols = [str(c).strip().lower() for c in df_test.columns]

        if (
            "city name" in cols
            and "year" in cols
            and "fatal" in cols
            and "non fatal" in cols
        ):
            d47_file = f
            break

    except Exception:
        pass

if d47_file is None:
    raise FileNotFoundError("D47 crime dataset could not be found.")

print("\nUsing D47 dataset:")
print(os.path.basename(d47_file))


# ============================================================
# 3. LOAD D47
# ============================================================

crime_df = pd.read_csv(d47_file)

crime_df.columns = crime_df.columns.str.strip()

# Remove total row
crime_df = crime_df[
    crime_df["Year"].astype(str).str.match(r"^\d{4}")
].copy()

crime_df["Year"] = (
    crime_df["Year"]
    .astype(str)
    .str.extract(r"(\d{4})")[0]
    .astype(int)
)

crime_df["Fatal"] = pd.to_numeric(
    crime_df["Fatal"], errors="coerce"
)

crime_df["Non fatal"] = pd.to_numeric(
    crime_df["Non fatal"], errors="coerce"
)

crime_df["Total Crimes"] = (
    crime_df["Fatal"] + crime_df["Non fatal"]
)

crime_df["Fatal %"] = (
    crime_df["Fatal"] /
    crime_df["Total Crimes"] * 100
).round(2)


# ============================================================
# 4. DISPLAY YEAR-WISE INSIGHTS
# ============================================================

print("\n========== URBANPULSE YEAR-WISE CRIME INSIGHTS ==========\n")

display(
    crime_df[
        [
            "Year",
            "Fatal",
            "Non fatal",
            "Total Crimes",
            "Fatal %"
        ]
    ].sort_values("Year", ascending=False)
)


# ============================================================
# 5. YEAR SELECTOR
# ============================================================

years = sorted(
    crime_df["Year"].unique(),
    reverse=True
)

year_dropdown = widgets.Dropdown(
    options=years,
    value=years[0],
    description="Year:",
    style={"description_width": "initial"}
)


# ============================================================
# 6. SHOW INSIGHTS FOR SELECTED YEAR
# ============================================================

def show_year_insight(year):

    row = crime_df[
        crime_df["Year"] == year
    ].iloc[0]

    print("\n" + "=" * 55)
    print(f"        URBANPULSE CRIME INSIGHT — {year}")
    print("=" * 55)

    print(f"\nTotal Crimes : {int(row['Total Crimes']):,}")
    print(f"Fatal Crimes : {int(row['Fatal']):,}")
    print(f"Non-Fatal Crimes : {int(row['Non fatal']):,}")
    print(f"Fatal Percentage : {row['Fatal %']:.2f}%")

    # Compare with previous available year
    previous = crime_df[
        crime_df["Year"] < year
    ].sort_values("Year", ascending=False)

    if len(previous) > 0:

        prev = previous.iloc[0]

        change = (
            (row["Total Crimes"] - prev["Total Crimes"])
            / prev["Total Crimes"] * 100
        )

        print(
            f"\nChange from {int(prev['Year'])}: "
            f"{change:+.2f}%"
        )

        if change > 0:
            print("Trend: Crime increased")
        elif change < 0:
            print("Trend: Crime decreased")
        else:
            print("Trend: No change")

    print("=" * 55)


widgets.interact(
    show_year_insight,
    year=year_dropdown
);

# ============================================================
# URBANPULSE — INTERACTIVE BENGALURU CRIME MAP
# YEAR SELECTOR + 150 KML LOCATIONS
# ============================================================

import folium
from IPython.display import display, clear_output
import ipywidgets as widgets

# ------------------------------------------------------------
# Create year selector
# ------------------------------------------------------------

map_year_dropdown = widgets.Dropdown(
    options=sorted(crime_df["Year"].unique(), reverse=True),
    value=max(crime_df["Year"]),
    description="Select Year:",
    style={"description_width": "initial"}
)

# ------------------------------------------------------------
# Function to create the map
# ------------------------------------------------------------

def create_crime_map(year):

    # Get selected year's actual data
    selected = crime_df[
        crime_df["Year"] == year
    ].iloc[0]

    total_crimes = int(selected["Total Crimes"])
    fatal = int(selected["Fatal"])
    non_fatal = int(selected["Non fatal"])
    fatal_pct = float(selected["Fatal %"])

    # --------------------------------------------------------
    # Create Bengaluru map
    # --------------------------------------------------------

    m = folium.Map(
        location=[12.9716, 77.5946],
        zoom_start=11,
        tiles="OpenStreetMap"
    )

    # --------------------------------------------------------
    # Add all 150 extracted KML locations
    # --------------------------------------------------------

    for _, row in police_df.iterrows():

        popup_html = f"""
        <div style="width:320px">

            <h3 style="margin-bottom:10px;">
                🚔 {row['Police Station']}
            </h3>

            <b>Location</b><br>
            Latitude: {row['Latitude']:.6f}<br>
            Longitude: {row['Longitude']:.6f}

            <hr>

            <h3>📊 UrbanPulse Crime Information</h3>

            <b>Selected Year:</b> {year}<br><br>

            <b>Total Crimes:</b>
            {total_crimes:,}<br>

            <b>Fatal Crimes:</b>
            {fatal:,}<br>

            <b>Non-Fatal Crimes:</b>
            {non_fatal:,}<br>

            <b>Fatal Percentage:</b>
            {fatal_pct:.2f}%

            <hr>

            <b>⚠️ Data Scope</b><br>

            These crime statistics are
            <b>Bengaluru city-level statistics</b>.
            The supplied crime dataset does not contain
            police-station-level crime counts.

        </div>
        """

        folium.Marker(
            location=[
                row["Latitude"],
                row["Longitude"]
            ],
            popup=folium.Popup(
                popup_html,
                max_width=380
            ),
            tooltip=row["Police Station"],
            icon=folium.Icon(
                icon="info-sign",
                prefix="glyphicon"
            )
        ).add_to(m)

    # --------------------------------------------------------
    # City-level information box
    # --------------------------------------------------------

    info_html = f"""
    <div style="
        position: fixed;
        top: 20px;
        right: 20px;
        width: 300px;
        z-index: 9999;
        background-color: white;
        border: 2px solid #222;
        border-radius: 15px;
        padding: 18px;
        font-family: Arial;
        box-shadow: 0 3px 10px rgba(0,0,0,0.3);
    ">

        <h2 style="margin-top:0;">
            🏙️ UrbanPulse
        </h2>

        <h3>Crime Overview</h3>

        <hr>

        <b>Selected Year:</b> {year}<br><br>

        <b>Total Crimes:</b>
        {total_crimes:,}<br><br>

        <b>Fatal Crimes:</b>
        {fatal:,}<br><br>

        <b>Non-Fatal Crimes:</b>
        {non_fatal:,}<br><br>

        <b>Fatal Percentage:</b>
        {fatal_pct:.2f}%

        <hr>

        <b>📍 Mapped Locations:</b>
        {len(police_df)}

        <hr>

        <small>
        Crime counts are Bengaluru city-level statistics.
        They are not assigned to individual police stations
        because the supplied crime dataset does not contain
        station-level crime counts.
        </small>

    </div>
    """

    m.get_root().html.add_child(
        folium.Element(info_html)
    )

    return m


# ------------------------------------------------------------
# Display map when year changes
# ------------------------------------------------------------

output = widgets.Output()

def update_map(change=None):

    with output:
        clear_output(wait=True)

        selected_year = map_year_dropdown.value

        crime_map = create_crime_map(
            selected_year
        )

        display(crime_map)


map_year_dropdown.observe(
    update_map,
    names="value"
)

display(map_year_dropdown)
display(output)

# Show map initially
update_map()

# ============================================================
# URBANPULSE - ADDITIONAL CRIME CATEGORY INSIGHTS
# Uses the supplied Bengaluru City Police PDF
# ============================================================

import glob
import re
import pandas as pd
import ipywidgets as widgets
from IPython.display import display, clear_output

# ------------------------------------------------------------
# 1. Find the supplied Bengaluru Police PDF automatically
# ------------------------------------------------------------

pdf_files = glob.glob("/content/*.pdf")

if not pdf_files:
    raise FileNotFoundError("No PDF found in /content")

print("PDF files found:")
for f in pdf_files:
    print(" -", f)

# Use the first PDF containing the relevant crime sections
crime_pdf = None

from pypdf import PdfReader

for f in pdf_files:
    try:
        reader = PdfReader(f)
        text = "\n".join(
            page.extract_text() or ""
            for page in reader.pages
        )

        if (
            "CRIMES AGAINST WOMEN" in text
            and "CRIMES AGAINST CHILDREN" in text
            and "CYBER CRIME" in text
        ):
            crime_pdf = f
            break

    except Exception:
        pass

if crime_pdf is None:
    raise FileNotFoundError(
        "Could not find the Bengaluru Police crime PDF."
    )

print("\nUsing:")
print(crime_pdf)

reader = PdfReader(crime_pdf)

pdf_text = "\n".join(
    page.extract_text() or ""
    for page in reader.pages
)

# ============================================================
# 2. DATA FROM THE SUPPLIED PDF
# ============================================================

# These dictionaries are created from the actual tables
# extracted from the supplied Bengaluru Police report.

women_data = {
    2021: {
        "Rape": (116, 116),
        "Molestation": (573, 559),
        "Insulting Modesty of Women": (19, 17),
        "Dowry Death": (26, 26),
        "Cruelty by Husband/Relatives": (422, 420),
        "Immoral Trafficking Act": (129, 129),
        "Indecent Representation of Women": (0, 0),
        "Dowry Prohibition Act": (735, 724),
    },
    2022: {
        "Rape": (152, 151),
        "Molestation": (731, 688),
        "Insulting Modesty of Women": (29, 24),
        "Dowry Death": (29, 29),
        "Cruelty by Husband/Relatives": (580, 573),
        "Immoral Trafficking Act": (155, 155),
        "Indecent Representation of Women": (0, 0),
        "Dowry Prohibition Act": (954, 925),
    },
    2023: {
        "Rape": (176, 176),
        "Molestation": (1135, 1004),
        "Insulting Modesty of Women": (60, 52),
        "Dowry Death": (25, 25),
        "Cruelty by Husband/Relatives": (696, 696),
        "Immoral Trafficking Act": (161, 161),
        "Indecent Representation of Women": (0, 0),
        "Dowry Prohibition Act": (1007, 1007),
    }
}


children_data = {
    2021: {
        "Exposure and Abandonment": (16, 3),
        "Concealment of Birth": (4, 1),
        "Juvenile Justice Act": (33, 33),
        "Child Labour Act": (9, 9),
        "Child Marriage Restraint Act": (14, 14),
        "POCSO Act": (403, 401),
        "Bonded Labour Act": (0, 0),
    },
    2022: {
        "Exposure and Abandonment": (12, 3),
        "Concealment of Birth": (12, 0),
        "Juvenile Justice Act": (37, 37),
        "Child Labour Act": (9, 9),
        "Child Marriage Restraint Act": (11, 11),
        "POCSO Act": (480, 477),
        "Bonded Labour Act": (0, 0),
    },
    2023: {
        "Exposure and Abandonment": (10, 0),
        "Concealment of Birth": (11, 0),
        "Juvenile Justice Act": (40, 40),
        "Child Labour Act": (4, 4),
        "Child Marriage Restraint Act": (6, 6),
        "POCSO Act": (560, 538),
        "Bonded Labour Act": (0, 0),
    }
}


# Cyber crime:
# (Reported, Detected, UI)
cyber_data = {
    2021: {
        "CENTRAL": (660, 166, 3),
        "WEST": (1148, 223, 2),
        "NORTH": (618, 319, 28),
        "SOUTH": (942, 285, 29),
        "EAST": (602, 198, 3),
        "NORTH EAST": (832, 130, 2),
        "SOUTH EAST": (735, 278, 13),
        "WHITE FIELD": (869, 653, 102),
        "CYBER PS. COP": (16, 5, 10),
    },

    2022: {
        "CENTRAL": (989, 173, 36),
        "WEST": (1384, 182, 81),
        "NORTH": (1300, 242, 597),
        "SOUTH": (1360, 578, 184),
        "EAST": (937, 129, 99),
        "NORTH EAST": (1550, 196, 5),
        "SOUTH EAST": (1329, 621, 281),
        "WHITE FIELD": (1055, 303, 519),
        "CYBER PS. COP": (36, 7, 27),
    },

    2023: {
        "CENTRAL": (1126, 69, 753),
        "WEST": (1941, 47, 1487),
        "NORTH": (3260, 238, 2809),
        "SOUTH": (2094, 224, 1351),
        "EAST": (1994, 129, 1750),
        "NORTH EAST": (1917, 201, 1371),
        "SOUTH EAST": (2674, 298, 2319),
        "WHITE FIELD": (2562, 55, 2394),
        "CYBER PS. COP": (55, 10, 51),
    }
}


accidental_data = {
    2021: {
        "Electrocution": (40, 9),
        "Drowning": (36, 14),
        "Burning": (40, 49),
        "Fall from Height": (155, 35),
        "Poisoning": (31, 5),
        "Others": (2181, 364),
    },

    2022: {
        "Electrocution": (43, 11),
        "Drowning": (50, 7),
        "Burning": (40, 44),
        "Fall from Height": (228, 32),
        "Poisoning": (30, 20),
        "Others": (2434, 421),
    },

    2023: {
        "Electrocution": (28, 5),
        "Drowning": (51, 18),
        "Burning": (53, 65),
        "Fall from Height": (186, 37),
        "Poisoning": (24, 18),
        "Others": (2574, 431),
    }
}


# ============================================================
# 3. INTERACTIVE CONTROLS
# ============================================================

category_dropdown = widgets.Dropdown(
    options=[
        "Crimes Against Women",
        "Crimes Against Children",
        "Cyber Crime",
        "Accidental Deaths"
    ],
    value="Crimes Against Women",
    description="Category:"
)

year_dropdown_2 = widgets.Dropdown(
    options=[2021, 2022, 2023],
    value=2023,
    description="Year:"
)

output = widgets.Output()


# ============================================================
# 4. DISPLAY FUNCTION
# ============================================================

def show_category_insight(change=None):

    with output:
        clear_output(wait=True)

        category = category_dropdown.value
        year = year_dropdown_2.value

        print("=" * 65)
        print(f"URBANPULSE | {category.upper()} | {year}")
        print("=" * 65)

        # ----------------------------------------------------
        # WOMEN
        # ----------------------------------------------------

        if category == "Crimes Against Women":

            data = women_data[year]

            rows = []

            for crime, values in data.items():
                reported, detected = values

                rows.append({
                    "Crime Type": crime,
                    "Reported": reported,
                    "Detected": detected,
                    "Detection %": round(
                        detected / reported * 100, 2
                    ) if reported else 0
                })

            df = pd.DataFrame(rows)

            print(f"\nTotal Reported: {df['Reported'].sum():,}")
            print(f"Total Detected: {df['Detected'].sum():,}")

            highest = df.loc[
                df["Reported"].idxmax()
            ]

            print(
                f"\nHighest Reported Crime: "
                f"{highest['Crime Type']}"
            )

            print(
                f"Reported Cases: "
                f"{highest['Reported']:,}"
            )

            display(df)

        # ----------------------------------------------------
        # CHILDREN
        # ----------------------------------------------------

        elif category == "Crimes Against Children":

            data = children_data[year]

            rows = []

            for crime, values in data.items():
                reported, detected = values

                rows.append({
                    "Crime Type": crime,
                    "Reported": reported,
                    "Detected": detected,
                    "Detection %": round(
                        detected / reported * 100, 2
                    ) if reported else 0
                })

            df = pd.DataFrame(rows)

            print(f"\nTotal Reported: {df['Reported'].sum():,}")
            print(f"Total Detected: {df['Detected'].sum():,}")

            highest = df.loc[
                df["Reported"].idxmax()
            ]

            print(
                f"\nHighest Reported Crime: "
                f"{highest['Crime Type']}"
            )

            print(
                f"Reported Cases: "
                f"{highest['Reported']:,}"
            )

            display(df)

        # ----------------------------------------------------
        # CYBER CRIME
        # ----------------------------------------------------

        elif category == "Cyber Crime":

            data = cyber_data[year]

            rows = []

            for division, values in data.items():

                reported, detected, ui = values

                rows.append({
                    "Police Division": division,
                    "Reported": reported,
                    "Detected": detected,
                    "UI": ui,
                    "Detection %": round(
                        detected / reported * 100, 2
                    ) if reported else 0
                })

            df = pd.DataFrame(rows)

            print(
                f"\nTotal Reported Cyber Crimes: "
                f"{df['Reported'].sum():,}"
            )

            print(
                f"Total Detected: "
                f"{df['Detected'].sum():,}"
            )

            highest = df.loc[
                df["Reported"].idxmax()
            ]

            print(
                f"\nHighest Reporting Division: "
                f"{highest['Police Division']}"
            )

            print(
                f"Reported Cases: "
                f"{highest['Reported']:,}"
            )

            display(df)

        # ----------------------------------------------------
        # ACCIDENTAL DEATHS
        # ----------------------------------------------------

        elif category == "Accidental Deaths":

            data = accidental_data[year]

            rows = []

            for cause, values in data.items():

                male, female = values

                rows.append({
                    "Cause": cause,
                    "Male": male,
                    "Female": female,
                    "Total": male + female
                })

            df = pd.DataFrame(rows)

            print(
                f"\nTotal Male: "
                f"{df['Male'].sum():,}"
            )

            print(
                f"Total Female: "
                f"{df['Female'].sum():,}"
            )

            print(
                f"Total Accidental Deaths: "
                f"{df['Total'].sum():,}"
            )

            highest = df.loc[
                df["Total"].idxmax()
            ]

            print(
                f"\nHighest Cause: "
                f"{highest['Cause']}"
            )

            print(
                f"Total: "
                f"{highest['Total']:,}"
            )

            display(df)


# ============================================================
# 5. CONNECT DROPDOWNS
# ============================================================

category_dropdown.observe(
    show_category_insight,
    names="value"
)

year_dropdown_2.observe(
    show_category_insight,
    names="value"
)


# ============================================================
# 6. DISPLAY
# ============================================================

display(
    widgets.VBox([
        widgets.HBox([
            category_dropdown,
            year_dropdown_2
        ]),
        output
    ])
)

show_category_insight()

from google.colab import files

uploaded = files.upload()

!pip install pymupdf

import os
import glob
import fitz  # PyMuPDF

pdf_files = glob.glob("/content/*.pdf")

print("PDF files found:")
for f in pdf_files:
    print(f)

if not pdf_files:
    print("\n❌ No PDF found. Please upload the Bengaluru Police PDF.")
else:
    pdf_path = pdf_files[0]

    print("\nUsing:")
    print(pdf_path)

    doc = fitz.open(pdf_path)

    print("\nNumber of pages:", len(doc))

    # Show text from the first few pages
    for i in range(min(5, len(doc))):
        text = doc[i].get_text()

        print("\n" + "="*70)
        print("PAGE", i + 1)
        print("="*70)
        print(text[:5000])

import glob
import fitz
import re

# Find the actual PDF
pdf_files = glob.glob("/content/*.pdf")

print("PDF files found:")
for f in pdf_files:
    print(f)

if not pdf_files:
    print("\n❌ No PDF found in /content")
else:
    pdf_path = pdf_files[0]
    print("\nUsing PDF:", pdf_path)

    doc = fitz.open(pdf_path)

    keywords = [
        "women",
        "woman",
        "children",
        "child",
        "cyber",
        "suicide",
        "accidental",
        "death",
        "crime"
    ]

    print("\nNumber of pages:", len(doc))

    for page_no, page in enumerate(doc):
        text = page.get_text("text")

        text_lower = text.lower()

        if any(keyword in text_lower for keyword in keywords):

            print("\n" + "=" * 100)
            print("PAGE:", page_no + 1)
            print("=" * 100)

            print(text[:12000])

import fitz
import pandas as pd
import re

# Open the PDF we already found
doc = fitz.open(pdf_path)

# Store every page's text
pages = []

for i, page in enumerate(doc):
    text = page.get_text("text")

    pages.append({
        "Page": i + 1,
        "Text": text
    })

pdf_pages_df = pd.DataFrame(pages)

print("Total PDF pages:", len(pdf_pages_df))

# Show a short preview of every page
for _, row in pdf_pages_df.iterrows():
    print("\n" + "=" * 100)
    print("PAGE", row["Page"])
    print("=" * 100)
    print(row["Text"][:3000])

!pip -q install pdfplumber

import pdfplumber
import pandas as pd
import os

print("Using PDF:")
print(pdf_path)

all_tables = []

with pdfplumber.open(pdf_path) as pdf:

    for page_no, page in enumerate(pdf.pages, start=1):

        tables = page.extract_tables()

        print(f"\nPAGE {page_no}: {len(tables)} table(s) found")

        for table_no, table in enumerate(tables, start=1):

            if table and len(table) > 1:

                df = pd.DataFrame(table)

                print(
                    f"   Table {table_no}: "
                    f"{df.shape[0]} rows × {df.shape[1]} columns"
                )

                all_tables.append({
                    "page": page_no,
                    "table": table_no,
                    "data": df
                })

for item in all_tables:

    print("\n" + "=" * 80)
    print(
        "PAGE:", item["page"],
        "| TABLE:", item["table"]
    )
    print("=" * 80)

    display(item["data"].head(15))

