# -*- coding: utf-8 -*-
"""urbanpulse _edaipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W1I36u7ckizPB6s19w7lKrCrole61DCs
"""

import os

matches = []

for root, dirs, files in os.walk("/"):
    for file in files:
        if file == "bbmp-2025-26-198-wards-work-orders.csv":
            matches.append(os.path.join(root, file))

print(matches)

import pandas as pd

# The dataset is currently unavailable on Kaggle, but a local copy seems to be present.
# Loading directly from the local path that worked previously.
csv_path = "/bbmp-2025-26-198-wards-work-orders.csv"

df_construction = pd.read_csv(csv_path)

print("Shape:", df_construction.shape)
display(df_construction.head())

# Create a copy for ward-level analysis

ward_df = df_construction.copy()

# Check the ward column
print("Number of unique wards:", ward_df["ward"].nunique())

print("\nWard values:")
print(ward_df["ward"].unique()[:20])

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Dataset shape:", df_construction.shape)

print("\nColumns:")
print(df_construction.columns.tolist())

print("\nData types:")
display(df_construction.dtypes.to_frame("Data Type"))

print("\nFirst 5 rows:")
display(df_construction.head())

missing = df_construction.isnull().sum()

missing_df = pd.DataFrame({
    "Missing Count": missing,
    "Missing %": (missing / len(df_construction) * 100).round(2)
})

display(
    missing_df[missing_df["Missing Count"] > 0]
    .sort_values("Missing Count", ascending=False)
)

print("Duplicate rows:", df_construction.duplicated().sum())

numeric_cols = df_construction.select_dtypes(include=np.number).columns.tolist()

print("Numerical columns:")
print(numeric_cols)

display(df_construction[numeric_cols].describe().T)

amount_cols = [
    col for col in df_construction.columns
    if any(word in col.lower() for word in
           ["amount", "cost", "value", "payment", "contract"])
]

print("Possible monetary columns:")
print(amount_cols)

for col in amount_cols:
    print(f"\n{col}")
    display(df_construction[col].describe())

ward_cols = [
    col for col in df_construction.columns
    if "ward" in col.lower()
]

print("Ward-related columns:")
print(ward_cols)

ward_col = ward_cols[0]

ward_counts = (
    df_construction[ward_col]
    .value_counts()
    .head(15)
)

display(ward_counts)

plt.figure(figsize=(10, 6))

ward_counts.sort_values().plot(kind="barh")

plt.title("Top Wards by Number of BBMP Work Orders")
plt.xlabel("Number of Work Orders")
plt.ylabel("Ward")

plt.tight_layout()
plt.show()

contractor_cols = [
    col for col in df_construction.columns
    if any(word in col.lower() for word in
           ["contractor", "agency", "vendor"])
]

print(contractor_cols)

contractor_col = contractor_cols[0]

top_contractors = (
    df_construction[contractor_col]
    .value_counts()
    .head(10)
)

display(top_contractors)

plt.figure(figsize=(10, 6))

top_contractors.sort_values().plot(kind="barh")

plt.title("Top Contractors by Number of BBMP Work Orders")
plt.xlabel("Number of Work Orders")
plt.ylabel("Contractor")

plt.tight_layout()
plt.show()

work_cols = [
    col for col in df_construction.columns
    if any(word in col.lower() for word in
           ["work", "description", "project", "nature"])
]

print("Work-related columns:")
print(work_cols)

work_cols = []

import pandas as pd

csv_path = "/bbmp-2025-26-198-wards-work-orders.csv"

df_construction = pd.read_csv(csv_path)

print("Shape:", df_construction.shape)
display(df_construction.head())

print("Construction dataset columns:")
for i, col in enumerate(df_construction.columns):
    print(i, repr(col))

print("\nShape:", df_construction.shape)
display(df_construction.head(5))

# ============================================
# FIND COST / VALUE COLUMNS
# ============================================

value_keywords = [
    "amount",
    "cost",
    "value",
    "budget",
    "estimate",
    "expenditure",
    "contract"
]

value_cols = []

for col in df_construction.columns:
    col_lower = col.lower()

    if any(keyword in col_lower for keyword in value_keywords):
        value_cols.append(col)

print("Possible monetary/value columns:")

for col in value_cols:
    print("-", col)

ward_col = "Ward Name"

# ============================================
# WORK ORDERS BY WARD
# ============================================

ward_summary = (
    df_construction
    .groupby(ward_col)
    .size()
    .sort_values(ascending=False)
    .reset_index(name="Work Orders")
)

display(ward_summary.head(20))

value_col = "Work Order Amount"

# ============================================
# INFRASTRUCTURE VALUE BY WARD
# ============================================

df_construction[value_col] = pd.to_numeric(
    df_construction[value_col],
    errors="coerce"
)

ward_value = (
    df_construction
    .groupby(ward_col)[value_col]
    .agg(
        Total_Value="sum",
        Average_Value="mean",
        Number_of_Works="count"
    )
    .sort_values("Total_Value", ascending=False)
)

display(ward_value.head(20))

# ============================================
# EXACT BBMP COLUMN NAMES
# ============================================

print("BBMP DATASET")
print("=" * 60)

print("Shape:", df_construction.shape)

print("\nEXACT COLUMN NAMES:")
for i, col in enumerate(df_construction.columns):
    print(f"{i}: {repr(col)}")

print("\nFIRST 5 ROWS:")
display(df_construction.head())

print("\nDATA TYPES:")
display(df_construction.dtypes.to_frame("Data Type"))

# ============================================
# CHECK ALL NUMERIC COLUMNS
# ============================================

numeric_cols = df_construction.select_dtypes(
    include="number"
).columns.tolist()

print("NUMERIC COLUMNS:")
for col in numeric_cols:
    print("-", repr(col))

print("\nOBJECT/TEXT COLUMNS:")
text_cols = df_construction.select_dtypes(
    include="object"
).columns.tolist()

for col in text_cols:
    print("-", repr(col))

# ============================================================
# BBMP CONSTRUCTION DATA — CLEANING
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Make a copy so the original dataset remains safe
construction = df_construction.copy()

# Clean ward names/values
construction["ward"] = construction["ward"].astype(str).str.strip()

# Convert financial columns to numeric
money_cols = ["amount", "nett", "deduction"]

for col in money_cols:
    construction[col] = pd.to_numeric(
        construction[col],
        errors="coerce"
    )

print("Dataset shape:", construction.shape)

print("\nMissing values:")
display(construction.isnull().sum().to_frame("Missing"))

print("\nDuplicate rows:", construction.duplicated().sum())

print("\nCleaned data:")
display(construction.head())

# ============================================================
# BASIC BBMP CONSTRUCTION STATISTICS
# ============================================================

print("TOTAL WORK ORDERS:", len(construction))

print("UNIQUE WARDS:", construction["ward"].nunique())

print("UNIQUE CONTRACTORS:", construction["contractor"].nunique())

print("\nFINANCIAL SUMMARY")
display(
    construction[
        ["amount", "nett", "deduction"]
    ].describe().round(2)
)

# ============================================================
# WORK ORDERS BY WARD
# ============================================================

ward_work_count = (
    construction
    .groupby("ward")
    .size()
    .sort_values(ascending=False)
    .reset_index(name="Work_Orders")
)

display(ward_work_count.head(20))

# ============================================================
# TOTAL INFRASTRUCTURE VALUE BY WARD
# ============================================================

ward_financial = (
    construction
    .groupby("ward")
    .agg(
        Work_Orders=("id", "count"),
        Total_Amount=("amount", "sum"),
        Average_Amount=("amount", "mean"),
        Total_Nett=("nett", "sum"),
        Total_Deduction=("deduction", "sum")
    )
    .reset_index()
)

ward_financial = ward_financial.sort_values(
    "Total_Amount",
    ascending=False
)

display(ward_financial.head(20))

# ============================================================
# TOP 15 WARDS BY TOTAL WORK VALUE
# ============================================================

top15_value = ward_financial.head(15)

plt.figure(figsize=(10, 6))

plt.barh(
    top15_value["ward"].astype(str)[::-1],
    top15_value["Total_Amount"][::-1]
)

plt.xlabel("Total Work Order Amount")
plt.ylabel("Ward")
plt.title("Top 15 Wards by Infrastructure Investment")

plt.tight_layout()
plt.show()

# ============================================================
# TOP CONTRACTORS
# ============================================================

contractor_summary = (
    construction
    .groupby("contractor")
    .agg(
        Work_Orders=("id", "count"),
        Total_Amount=("amount", "sum")
    )
    .sort_values(
        "Total_Amount",
        ascending=False
    )
)

display(contractor_summary.head(15))

# ============================================================
# DEDUCTION ANALYSIS
# ============================================================

construction["Deduction_Rate"] = np.where(
    construction["amount"] > 0,
    (construction["deduction"] / construction["amount"]) * 100,
    np.nan
)

print("Average deduction rate:",
      round(construction["Deduction_Rate"].mean(), 2), "%")

display(
    construction[
        ["amount", "nett", "deduction", "Deduction_Rate"]
    ].describe().round(2)
)

# ============================================================
# WARD-LEVEL FEATURES FOR K-MEANS++
# ============================================================

ward_features = (
    construction
    .groupby("ward")
    .agg(
        Work_Order_Count=("id", "count"),
        Total_Amount=("amount", "sum"),
        Average_Amount=("amount", "mean"),
        Total_Nett=("nett", "sum"),
        Total_Deduction=("deduction", "sum")
    )
    .reset_index()
)

# Calculate deduction percentage at ward level
ward_features["Deduction_Rate"] = np.where(
    ward_features["Total_Amount"] > 0,
    (
        ward_features["Total_Deduction"]
        / ward_features["Total_Amount"]
    ) * 100,
    0
)

display(ward_features.head(10))

print("Number of wards:", len(ward_features))

# ============================================================
# LOG TRANSFORMATION
# ============================================================

features = [
    "Work_Order_Count",
    "Total_Amount",
    "Average_Amount",
    "Total_Nett",
    "Total_Deduction",
    "Deduction_Rate"
]

X = ward_features[features].copy()

# Replace infinite values
X = X.replace([np.inf, -np.inf], np.nan)

# Fill missing values
X = X.fillna(0)

# Log transform positive-skewed variables
log_features = [
    "Work_Order_Count",
    "Total_Amount",
    "Average_Amount",
    "Total_Nett",
    "Total_Deduction"
]

for col in log_features:
    X[col] = np.log1p(X[col])

display(X.head())

# ============================================================
# STANDARDIZATION
# ============================================================

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print("Scaled feature matrix:", X_scaled.shape)

# ============================================================
# ELBOW + SILHOUETTE
# ============================================================

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

k_values = range(2, 9)

inertias = []
silhouette_scores = []

for k in k_values:

    model = KMeans(
        n_clusters=k,
        init="k-means++",
        n_init=10,
        random_state=42
    )

    labels = model.fit_predict(X_scaled)

    inertias.append(model.inertia_)

    silhouette_scores.append(
        silhouette_score(X_scaled, labels)
    )

# ---------------- ELBOW ----------------

plt.figure(figsize=(8, 5))

plt.plot(
    list(k_values),
    inertias,
    marker="o"
)

plt.xlabel("Number of Clusters (K)")
plt.ylabel("Inertia")
plt.title("Elbow Method — BBMP Infrastructure")

plt.grid(True)
plt.show()


# ---------------- SILHOUETTE ----------------

plt.figure(figsize=(8, 5))

plt.plot(
    list(k_values),
    silhouette_scores,
    marker="o"
)

plt.xlabel("Number of Clusters (K)")
plt.ylabel("Silhouette Score")
plt.title("Silhouette Score — BBMP Infrastructure")

plt.grid(True)
plt.show()


# Print scores
print("\nSILHOUETTE SCORES")

for k, score in zip(k_values, silhouette_scores):
    print(f"K = {k}: {score:.4f}")

# ============================================================
# FINAL K-MEANS++
# ============================================================

BEST_K = 4   # CHANGE THIS AFTER ELBOW + SILHOUETTE

kmeans = KMeans(
    n_clusters=BEST_K,
    init="k-means++",
    n_init=10,
    random_state=42
)

ward_features["Cluster"] = kmeans.fit_predict(X_scaled)

display(
    ward_features.sort_values(
        "Cluster"
    )
)

# ============================================================
# CLUSTER PROFILES
# ============================================================

profile = (
    ward_features
    .groupby("Cluster")[
        [
            "Work_Order_Count",
            "Total_Amount",
            "Average_Amount",
            "Total_Nett",
            "Total_Deduction",
            "Deduction_Rate"
        ]
    ]
    .mean()
    .round(2)
)

display(profile)

# ============================================================
# WARDS INSIDE EACH CLUSTER
# ============================================================

for cluster in sorted(
    ward_features["Cluster"].unique()
):

    print("\n" + "=" * 60)
    print(f"CLUSTER {cluster}")
    print("=" * 60)

    display(
        ward_features[
            ward_features["Cluster"] == cluster
        ]
        .sort_values(
            "Total_Amount",
            ascending=False
        )
        .head(15)
    )

# ============================================================
# PCA VISUALIZATION
# ============================================================

from sklearn.decomposition import PCA

pca = PCA(n_components=2)

X_pca = pca.fit_transform(X_scaled)

ward_features["PCA1"] = X_pca[:, 0]
ward_features["PCA2"] = X_pca[:, 1]

print(
    "Variance explained:",
    round(pca.explained_variance_ratio_.sum() * 100, 2),
    "%"
)

plt.figure(figsize=(10, 7))

for cluster in sorted(
    ward_features["Cluster"].unique()
):

    subset = ward_features[
        ward_features["Cluster"] == cluster
    ]

    plt.scatter(
        subset["PCA1"],
        subset["PCA2"],
        label=f"Cluster {cluster}",
        alpha=0.75
    )

plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")

plt.title(
    "Bengaluru Infrastructure Activity — K-Means++ Clusters"
)

plt.legend()
plt.grid(True)

plt.show()

# ============================================================
# COMPARE K=2 VS K=4
# ============================================================

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

for k in [2, 4]:

    model = KMeans(
        n_clusters=k,
        init="k-means++",
        n_init=20,
        random_state=42
    )

    labels = model.fit_predict(X_scaled)

    score = silhouette_score(X_scaled, labels)

    print(f"K = {k}")
    print(f"Silhouette Score = {score:.4f}")
    print(f"Inertia = {model.inertia_:.2f}")
    print("-" * 40)

!find / -path "*banglore-city-traffic-dataset*" 2>/dev/null

import kagglehub
import os

path = kagglehub.dataset_download(
    "preethamgouda/banglore-city-traffic-dataset"
)

print("Dataset path:")
print(path)

print("\nFiles inside:")
print(os.listdir(path))

import pandas as pd
import os

files = os.listdir(path)
print(files)

csv_file = [f for f in files if f.endswith(".csv")][0]

df = pd.read_csv(os.path.join(path, csv_file))

print("Shape:", df.shape)
display(df.head())
print("\nColumns:")
print(df.columns.tolist())

import kagglehub
import os
import pandas as pd

# Download dataset
path = kagglehub.dataset_download(
    "preethamgouda/banglore-city-traffic-dataset"
)

print("Dataset path:", path)
print("Files:", os.listdir(path))

csv_files = [
    f for f in os.listdir(path)
    if f.lower().endswith(".csv")
]

print("CSV files found:", csv_files)

df_traffic = pd.read_csv(
    os.path.join(path, csv_files[0])
)

print("Shape:", df_traffic.shape)
display(df_traffic.head())

print("TRAFFIC DATASET")
print("=" * 60)

print("Shape:", df_traffic.shape)

print("\nColumns:")
for i, col in enumerate(df_traffic.columns):
    print(i, repr(col))

print("\nData Types:")
display(df_traffic.dtypes.to_frame("Data Type"))

print("\nFirst 5 rows:")
display(df_traffic.head())

# ============================================================
# TRAFFIC CLUSTERING FEATURES
# ============================================================

traffic_features = [
    "Traffic Volume",
    "Average Speed",
    "Travel Time Index",
    "Congestion Level",
    "Road Capacity Utilization",
    "Incident Reports"
]

# Keep only columns that actually exist
traffic_features = [
    col for col in traffic_features
    if col in df_traffic.columns
]

print("Features used for traffic clustering:")
print(traffic_features)

scaler = StandardScaler()

X_traffic_scaled = scaler.fit_transform(
    traffic_ml
)

print("Traffic data scaled successfully.")

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

k_values = range(2, 9)

traffic_inertia = []
traffic_silhouette = []

for k in k_values:

    model = KMeans(
        n_clusters=k,
        init="k-means++",
        n_init=20,
        random_state=42
    )

    labels = model.fit_predict(X_traffic_scaled)

    traffic_inertia.append(model.inertia_)
    traffic_silhouette.append(
        silhouette_score(
            X_traffic_scaled,
            labels
        )
    )

# -------------------------------
# Elbow
# -------------------------------

plt.figure(figsize=(8,5))

plt.plot(
    list(k_values),
    traffic_inertia,
    marker="o"
)

plt.xlabel("Number of Clusters (K)")
plt.ylabel("Inertia")
plt.title("Elbow Method — Bengaluru Traffic")

plt.grid(True)
plt.show()


# -------------------------------
# Silhouette
# -------------------------------

plt.figure(figsize=(8,5))

plt.plot(
    list(k_values),
    traffic_silhouette,
    marker="o"
)

plt.xlabel("Number of Clusters (K)")
plt.ylabel("Silhouette Score")
plt.title("Silhouette Score — Bengaluru Traffic")

plt.grid(True)
plt.show()


# -------------------------------
# Scores
# -------------------------------

print("\nTRAFFIC SILHOUETTE SCORES")

for k, score in zip(
    k_values,
    traffic_silhouette
):

    print(
        f"K = {k}: {score:.4f}"
    )

best_traffic_k = list(k_values)[
    np.argmax(traffic_silhouette)
]

print(
    "Best K according to silhouette:",
    best_traffic_k
)

traffic_kmeans = KMeans(
    n_clusters=best_traffic_k,
    init="k-means++",
    n_init=20,
    random_state=42
)

df_traffic["Traffic_Cluster"] = (
    traffic_kmeans.fit_predict(
        X_traffic_scaled
    )
)

print(
    "Traffic clustering completed."
)

traffic_profile = (
    df_traffic
    .groupby("Traffic_Cluster")[traffic_features]
    .mean()
    .round(2)
)

display(traffic_profile)

traffic_cluster_names = {
    0: "Low Traffic",
    1: "Moderate Traffic",
    2: "High Congestion"
}

df_traffic["Traffic_Profile"] = (
    df_traffic["Traffic_Cluster"]
    .map(traffic_cluster_names)
)

# ============================================
# CLASSIFY K-MEANS CLUSTERS
# ============================================

# Map cluster numbers to meaningful traffic categories
traffic_cluster_names = {
    0: "Low Traffic",
    1: "Moderate Traffic",
    2: "High Congestion"
}

# Create a new column with the traffic classification
df_traffic["Traffic_Profile"] = (
    df_traffic["Traffic_Cluster"]
    .map(traffic_cluster_names)
)

# Display the classification
print("Traffic Classification:")
display(
    df_traffic[
        ["Traffic_Cluster", "Traffic_Profile"]
    ].head(10)
)

# ============================================
# CREATE CLUSTER SUMMARY
# ============================================

traffic_profile = (
    df_traffic
    .groupby(
        ["Traffic_Cluster", "Traffic_Profile"]
    )[traffic_features]
    .mean()
    .round(2)
    .reset_index()
)

display(traffic_profile)

"""# **Clustering the traffic and construction datasets**

"""

print("Possible location columns:")

for col in df_traffic.columns:

    name = col.lower()

    if any(
        word in name
        for word in [
            "ward",
            "area",
            "location",
            "zone",
            "region",
            "road",
            "intersection"
        ]
    ):

        print(repr(col))

construction_ward = (
    df_construction
    .groupby("ward")
    .agg(
        Work_Orders=("id", "count"),
        Total_Investment=("amount", "sum"),
        Average_Project=("amount", "mean")
    )
    .reset_index()
)

# ============================================================
# FIND THE LOCATION COLUMN IN TRAFFIC DATA
# ============================================================

print("TRAFFIC DATASET COLUMNS")
print("=" * 60)

for i, col in enumerate(df_traffic.columns):
    print(i, repr(col))

print("\nPossible location-related columns:")
print("=" * 60)

for col in df_traffic.columns:
    c = str(col).lower()

    if any(word in c for word in [
        "ward",
        "area",
        "location",
        "zone",
        "region",
        "road",
        "junction",
        "street",
        "name"
    ]):
        print(repr(col))

print("\nTRAFFIC SAMPLE")
display(df_traffic.head(10))

# ============================================================
# TRAFFIC ANALYSIS BY AREA
# ============================================================

traffic_area = (
    df_traffic
    .groupby("Area Name")
    .agg(
        Traffic_Volume=("Traffic Volume", "mean"),
        Average_Speed=("Average Speed", "mean"),
        Congestion=("Congestion Level", "mean"),
        Capacity_Utilization=("Road Capacity Utilization", "mean"),
        Incidents=("Incident Reports", "mean"),
        Environmental_Impact=("Environmental Impact", "mean"),
        Public_Transport=("Public Transport Usage", "mean"),
        Pedestrian_Cyclist=("Pedestrian and Cyclist Count", "mean")
    )
    .reset_index()
)

traffic_area.head(20)

# ============================================================
# TOP TRAFFIC AREAS
# ============================================================

print("TOP AREAS BY TRAFFIC VOLUME")
display(
    traffic_area
    .sort_values("Traffic_Volume", ascending=False)
    .head(15)
)

print("\nTOP AREAS BY CONGESTION")
display(
    traffic_area
    .sort_values("Congestion", ascending=False)
    .head(15)
)

print("\nTOP AREAS BY ROAD CAPACITY UTILIZATION")
display(
    traffic_area
    .sort_values("Capacity_Utilization", ascending=False)
    .head(15)
)

# ============================================================
# TRAFFIC PRESSURE SCORE
# ============================================================

from sklearn.preprocessing import MinMaxScaler

traffic_score = traffic_area.copy()

score_cols = [
    "Traffic_Volume",
    "Congestion",
    "Capacity_Utilization",
    "Incidents"
]

scaler = MinMaxScaler()

traffic_score[
    [col + "_Norm" for col in score_cols]
] = scaler.fit_transform(
    traffic_score[score_cols]
)

traffic_score["Traffic_Pressure_Score"] = (
    traffic_score["Traffic_Volume_Norm"] * 0.30 +
    traffic_score["Congestion_Norm"] * 0.30 +
    traffic_score["Capacity_Utilization_Norm"] * 0.25 +
    traffic_score["Incidents_Norm"] * 0.15
) * 100

traffic_score = traffic_score.sort_values(
    "Traffic_Pressure_Score",
    ascending=False
)

display(
    traffic_score[
        [
            "Area Name",
            "Traffic_Volume",
            "Average_Speed",
            "Congestion",
            "Capacity_Utilization",
            "Incidents",
            "Traffic_Pressure_Score"
        ]
    ].head(20)
)

# ============================================================
# TRAFFIC RISK CATEGORY
# ============================================================

def traffic_category(score):
    if score >= 70:
        return "High Traffic Pressure"
    elif score >= 40:
        return "Moderate Traffic Pressure"
    else:
        return "Low Traffic Pressure"

traffic_score["Traffic_Category"] = (
    traffic_score["Traffic_Pressure_Score"]
    .apply(traffic_category)
)

display(
    traffic_score[
        [
            "Area Name",
            "Traffic_Pressure_Score",
            "Traffic_Category"
        ]
    ].head(20)
)

# ============================================================
# K-MEANS TRAFFIC CLUSTERING
# ============================================================

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

traffic_features = [
    "Traffic_Volume",
    "Average_Speed",
    "Congestion",
    "Capacity_Utilization",
    "Incidents",
    "Environmental_Impact",
    "Public_Transport",
    "Pedestrian_Cyclist"
]

X_traffic = traffic_score[traffic_features].copy()

X_traffic = X_traffic.replace(
    [np.inf, -np.inf],
    np.nan
)

X_traffic = X_traffic.fillna(X_traffic.median())

scaler = StandardScaler()
X_traffic_scaled = scaler.fit_transform(X_traffic)

print("Number of traffic areas:", len(X_traffic_scaled))
print("Traffic areas:")
display(traffic_score["Area Name"])

# ============================================================
# SAFE K-MEANS++ MODEL SELECTION FOR TRAFFIC
# ============================================================

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import numpy as np
import matplotlib.pyplot as plt

# ============================================================
# FINAL TRAFFIC K-MEANS++
# ============================================================

BEST_K_TRAFFIC = 4

traffic_kmeans = KMeans(
    n_clusters=BEST_K_TRAFFIC,
    init="k-means++",
    n_init=10,
    random_state=42
)

traffic_score["Traffic_Cluster"] = (
    traffic_kmeans.fit_predict(X_traffic_scaled)
)

display(
    traffic_score[
        [
            "Area Name",
            "Traffic_Volume",
            "Average_Speed",
            "Congestion",
            "Capacity_Utilization",
            "Incidents",
            "Traffic_Pressure_Score",
            "Traffic_Cluster"
        ]
    ].sort_values("Traffic_Cluster")
)

# ============================================================
# TRAFFIC CLUSTER PROFILES
# ============================================================

traffic_profile = (
    traffic_score
    .groupby("Traffic_Cluster")
    [
        [
            "Traffic_Volume",
            "Average_Speed",
            "Congestion",
            "Capacity_Utilization",
            "Incidents",
            "Environmental_Impact",
            "Traffic_Pressure_Score"
        ]
    ]
    .mean()
    .round(2)
)

display(traffic_profile)

"""Cluster 0 — Low-pressure areas
Lower traffic volume, better speeds and lower congestion.
Cluster 1 — Congestion-heavy areas
High congestion and high capacity utilization.
Cluster 2 — High-volume corridors
Large traffic volume but relatively better movement.
Cluster 3 — Critical traffic areas
High traffic + poor speed + high congestion + high incidents.
"""

# ============================================================
# AREAS INSIDE EACH TRAFFIC CLUSTER
# ============================================================

for cluster in sorted(
    traffic_score["Traffic_Cluster"].unique()
):

    print("\n" + "="*60)
    print(f"TRAFFIC CLUSTER {cluster}")
    print("="*60)

    display(
        traffic_score[
            traffic_score["Traffic_Cluster"] == cluster
        ][
            [
                "Area Name",
                "Traffic_Volume",
                "Average_Speed",
                "Congestion",
                "Capacity_Utilization",
                "Incidents",
                "Traffic_Pressure_Score"
            ]
        ]
        .sort_values(
            "Traffic_Pressure_Score",
            ascending=False
        )
        .head(15)
    )

print("Number of unique dates:", df["Date"].nunique())

print("\nDate range:")
print(df["Date"].min(), "to", df["Date"].max())

print("\nAreas:")
print(df["Area Name"].nunique())

display(
    df.groupby("Area Name")["Date"]
      .agg(["min", "max", "count"])
      .sort_values("count", ascending=False)
      .head(20)
)

# STEP 4.1 — Fix Date column

model_df = df_traffic.copy()

# Convert Date to datetime
model_df["Date"] = pd.to_datetime(
    model_df["Date"],
    errors="coerce"
)

# Check
print("Date datatype:", model_df["Date"].dtype)
print("Missing dates:", model_df["Date"].isna().sum())

display(model_df[["Date", "Area Name", "Traffic Volume"]].head())

# STEP 4.2 — Create time-based features

model_df["Year"] = model_df["Date"].dt.year
model_df["Month"] = model_df["Date"].dt.month
model_df["Day"] = model_df["Date"].dt.day
model_df["DayOfWeek"] = model_df["Date"].dt.dayofweek
model_df["DayOfYear"] = model_df["Date"].dt.dayofyear

# 1 = weekend, 0 = weekday
model_df["IsWeekend"] = (
    model_df["DayOfWeek"] >= 5
).astype(int)

display(
    model_df[
        [
            "Date",
            "Area Name",
            "Year",
            "Month",
            "Day",
            "DayOfWeek",
            "IsWeekend"
        ]
    ].head(10)
)

# STEP 4.3 — Construction feature

print(
    model_df["Roadwork and Construction Activity"]
    .value_counts(dropna=False)
)

# STEP 4.3 — Convert construction activity to numeric

model_df["Construction"] = (
    model_df["Roadwork and Construction Activity"]
    .map({
        "No": 0,
        "Yes": 1
    })
)

print("Construction feature:")
print(model_df["Construction"].value_counts(dropna=False))

display(
    model_df[
        [
            "Date",
            "Area Name",
            "Roadwork and Construction Activity",
            "Construction"
        ]
    ].head(10)
)

# STEP 4.4 — Create historical traffic features

# Make sure data is sorted correctly
model_df = model_df.sort_values(
    ["Area Name", "Date"]
).copy()

# Previous day's traffic
model_df["Traffic_Lag_1"] = (
    model_df.groupby("Area Name")["Traffic Volume"]
    .shift(1)
)

# Traffic 2 records/days earlier
model_df["Traffic_Lag_2"] = (
    model_df.groupby("Area Name")["Traffic Volume"]
    .shift(2)
)

# Traffic 7 records/days earlier
model_df["Traffic_Lag_7"] = (
    model_df.groupby("Area Name")["Traffic Volume"]
    .shift(7)
)

# Traffic 14 records/days earlier
model_df["Traffic_Lag_14"] = (
    model_df.groupby("Area Name")["Traffic Volume"]
    .shift(14)
)

# Previous 7-record average
model_df["Traffic_Rolling_7"] = (
    model_df.groupby("Area Name")["Traffic Volume"]
    .transform(
        lambda x: x.shift(1).rolling(7).mean()
    )
)

display(
    model_df[
        [
            "Date",
            "Area Name",
            "Traffic Volume",
            "Construction",
            "Traffic_Lag_1",
            "Traffic_Lag_2",
            "Traffic_Lag_7",
            "Traffic_Lag_14",
            "Traffic_Rolling_7"
        ]
    ].head(20)
)

# STEP 4.5 — Remove rows without sufficient history

before = len(model_df)

model_df = model_df.dropna(
    subset=[
        "Traffic_Lag_1",
        "Traffic_Lag_2",
        "Traffic_Lag_7",
        "Traffic_Lag_14",
        "Traffic_Rolling_7"
    ]
).copy()

after = len(model_df)

print("Rows before:", before)
print("Rows after:", after)
print("Rows removed:", before - after)

# STEP 4.6 — Final check

print("DATASET SHAPE:", model_df.shape)

display(
    model_df[
        [
            "Date",
            "Area Name",
            "Traffic Volume",
            "Construction",
            "Traffic_Lag_1",
            "Traffic_Lag_7",
            "Traffic_Lag_14",
            "Traffic_Rolling_7"
        ]
    ].head(15)
)

# Reload the Bangalore Traffic dataset

import kagglehub
import os
import pandas as pd

path = kagglehub.dataset_download(
    "preethamgouda/banglore-city-traffic-dataset"
)

print("Dataset path:", path)

# Find CSV file
csv_files = [
    f for f in os.listdir(path)
    if f.lower().endswith(".csv")
]

print("CSV files:", csv_files)

# Load the dataset
df_traffic = pd.read_csv(
    os.path.join(path, csv_files[0])
)

print("Shape:", df_traffic.shape)
display(df_traffic.head())

import pandas as pd

csv_path = "/bbmp-2025-26-198-wards-work-orders.csv"

df_construction = pd.read_csv(csv_path)

print("Shape:", df_construction.shape)
display(df_construction.head())

ward_features = ward_df.groupby("ward").agg(
    total_work_orders=("id", "count"),
    total_amount=("amount", "sum"),
    avg_project_amount=("amount", "mean"),
    total_net_expenditure=("nett", "sum"),
    avg_net_amount=("nett", "mean"),
    total_deduction=("deduction", "sum"),
    avg_deduction=("deduction", "mean"),
    unique_contractors=("contractor", "nunique")
).reset_index()

print("Ward-level dataset shape:", ward_features.shape)

display(ward_features.head())

# Create civic work categories from work descriptions

text = ward_df["wodetails"].fillna("").str.lower()

ward_df["is_drain"] = text.str.contains(
    "drain|drainage", regex=True
).astype(int)

ward_df["is_road"] = text.str.contains(
    "road|street", regex=True
).astype(int)

ward_df["is_maintenance"] = text.str.contains(
    "maintenance|repair", regex=True
).astype(int)

ward_df["is_development"] = text.str.contains(
    "development|improvement", regex=True
).astype(int)

ward_df["is_water"] = text.str.contains(
    "water|pipeline|sewer", regex=True
).astype(int)

print("Civic categories created.")

work_categories = ward_df.groupby("ward").agg(
    drain_projects=("is_drain", "sum"),
    road_projects=("is_road", "sum"),
    maintenance_projects=("is_maintenance", "sum"),
    development_projects=("is_development", "sum"),
    water_projects=("is_water", "sum")
).reset_index()

ward_features = ward_features.merge(
    work_categories,
    on="ward",
    how="left"
)

print("Updated shape:", ward_features.shape)

display(ward_features.head())

cluster_features = [
    "total_work_orders",
    "total_amount",
    "avg_project_amount",
    "total_net_expenditure",
    "avg_net_amount",
    "total_deduction",
    "avg_deduction",
    "unique_contractors",
    "drain_projects",
    "road_projects",
    "maintenance_projects",
    "development_projects",
    "water_projects"
]

X = ward_features[cluster_features]

print("Clustering data shape:", X.shape)
display(X.head())

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print("Scaled data shape:", X_scaled.shape)

"""### k-**means**"""

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

inertia = []

for k in range(2, 11):
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8, 5))
plt.plot(range(2, 11), inertia, marker="o")
plt.xlabel("Number of Clusters (K)")
plt.ylabel("Inertia")
plt.title("Elbow Method")
plt.show()

from sklearn.cluster import KMeans

kmeans = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=10
)

ward_features["cluster"] = kmeans.fit_predict(X_scaled)

print("Clusters created:")
print(ward_features["cluster"].value_counts().sort_index())

from sklearn.metrics import silhouette_score

score = silhouette_score(X_scaled, ward_features["cluster"])

print("Silhouette Score:", round(score, 3))

from sklearn.metrics import silhouette_score

results = {}

for k in range(2, 9):
    model = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    labels = model.fit_predict(X_scaled)
    score = silhouette_score(X_scaled, labels)
    results[k] = score

print("Silhouette Scores:")
for k, score in results.items():
    print(f"K={k}: {score:.3f}")

best_k = max(results, key=results.get)

print("Best K:", best_k)
print("Best Silhouette Score:", round(results[best_k], 3))

final_kmeans = KMeans(
    n_clusters=2,
    random_state=42,
    n_init=10
)

ward_features["cluster"] = final_kmeans.fit_predict(X_scaled)

print(ward_features["cluster"].value_counts().sort_index())

cluster_summary = ward_features.groupby("cluster")[cluster_features].mean()

display(cluster_summary)

# Compare the two clusters
cluster_summary = ward_features.groupby("cluster")[cluster_features].mean()

display(cluster_summary)

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))

plt.scatter(
    ward_features["total_amount"],
    ward_features["total_work_orders"],
    c=ward_features["cluster"],
    s=60
)

plt.xlabel("Total Amount")
plt.ylabel("Total Work Orders")
plt.title("Ward Clusters")
plt.show()

# Show wards in each cluster
cluster_wards = ward_features[["ward", "cluster"]].sort_values("cluster")

display(cluster_wards)

# Add meaningful cluster names
ward_features["cluster_name"] = ward_features["cluster"].map({
    0: "High Development / High Expenditure",
    1: "Low Development / Low Expenditure"
})

display(
    ward_features[["ward", "cluster", "cluster_name"]]
    .sort_values("cluster")
)

# Top 10 highest-expenditure wards
top_wards = ward_features.sort_values(
    "total_amount", ascending=False
)[["ward", "cluster", "cluster_name", "total_amount", "total_work_orders"]]

display(top_wards.head(10))

cluster_summary = ward_features.groupby("cluster")[
    cluster_features
].mean()

display(cluster_summary)

cluster_summary.T

# Final cluster comparison
comparison = cluster_summary.T.copy()

comparison["Difference_%"] = (
    (comparison[0] - comparison[1]) / comparison[1] * 100
)

display(comparison)

final_summary = ward_features.groupby("cluster").agg(
    wards=("ward", "count"),
    avg_work_orders=("total_work_orders", "mean"),
    avg_total_amount=("total_amount", "mean"),
    avg_net_expenditure=("total_net_expenditure", "mean"),
    avg_contractors=("unique_contractors", "mean")
).round(2)

display(final_summary)

import matplotlib.pyplot as plt

# Count wards in each cluster
cluster_counts = ward_features["cluster_name"].value_counts()

plt.figure(figsize=(8, 5))
cluster_counts.plot(kind="bar")

plt.xlabel("Cluster")
plt.ylabel("Number of Wards")
plt.title("Number of Wards in Each Development Cluster")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

# Visualize the two clusters

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))

for cluster in sorted(ward_features["cluster"].unique()):
    data = ward_features[ward_features["cluster"] == cluster]

    plt.scatter(
        data["total_work_orders"],
        data["total_amount"],
        label=data["cluster_name"].iloc[0],
        s=70,
        alpha=0.7
    )

plt.xlabel("Total Work Orders")
plt.ylabel("Total Project Amount")
plt.title("Ward Clusters: Work Orders vs Project Expenditure")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

